version: "3.8"
services:
  app:
    container_name: image-upload
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/usr/src/app/uploads # Only map the uploads folder
    environment:
      - PORT=8080
      - UPLOADS_DIR=/usr/src/app/uploads
    command: ["node", "dist/app.js"]
